authors:
  dmiron:
    name: G. Dan Miron
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/44091914
    url: https://github.com/gdmiron
  dkulik:
    name: Dmitrii Kulik
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/52164624
    url: https://github.com/dimitrikulik